version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: test-of-kathiyavad-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: testOfKathiyavad
    ports:
      - "5433:5432" # Host Port : Container Port
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
